/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (106, N'SystemAdmin', N'System Administrator', N'sa', NULL, CAST(N'2010-07-27T18:48:47.300' AS DateTime), NULL, 1, N'SA', NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (107, N'AIS', N'Adamas International School', N'sa', NULL, CAST(N'2012-08-24T12:20:09.520' AS DateTime), NULL, 1, N'AS', NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (108, N'AIT', N'Adamas Institute Of Technology', N'sa', NULL, CAST(N'2012-08-24T17:30:58.753' AS DateTime), NULL, 1, N'AT', NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (109, N'RICE Private Limited', N'Roys Institute of Competitive Examination Private Limited', N'sa', NULL, CAST(N'2012-08-25T14:06:19.437' AS DateTime), NULL, 1, N'RC', N'U80903WB2000PTC090934', N'AACCR4567N')
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (110, N'AWS', N'Adamas World School', N'sa', NULL, CAST(N'2012-10-05T11:32:08.973' AS DateTime), NULL, 1, N'AW', NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (111, N'Adamas Career', N'Adamas Career', N'sa', NULL, CAST(N'2012-10-05T11:52:06.097' AS DateTime), NULL, 1, N'AC', NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (112, N'AHSMS', N'Adamas Higher Secondary Model School', N'rice-group-admin', NULL, CAST(N'2015-04-28T11:31:23.133' AS DateTime), NULL, 1, N'AH', NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (113, N'Kidz', N'Adamas Kidz', N'RICE-GROUP-ADMIN', NULL, CAST(N'2023-10-19T18:45:53.050' AS DateTime), NULL, 1, NULL, NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (114, N'AKidz', N'Adamas Kidz School', N'RICE-GROUP-ADMIN', NULL, CAST(N'2023-10-19T18:47:11.427' AS DateTime), NULL, 1, NULL, NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (115, N'AdamasKidz', N'Adamas Kidz School Test', N'RICE-GROUP-ADMIN', NULL, CAST(N'2023-10-31T10:49:06.627' AS DateTime), NULL, 1, NULL, NULL, NULL)
INSERT [dbo].[T_Brand_Master] ([I_Brand_ID], [S_Brand_Code], [S_Brand_Name], [S_Crtd_By], [S_Upd_By], [Dt_Crtd_On], [Dt_Upd_On], [I_Status], [S_Short_Code], [S_CIN], [S_PAN]) VALUES (116, N'Dayanand School', N'Dayanand SChool', N'sa', NULL, CAST(N'2024-02-07T00:00:00.000' AS DateTime), NULL, 1, N'DS', NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[T_School_Academic_Session_Master] ON 

INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (1, 110, CAST(N'2023-04-01T00:00:00.000' AS DateTime), CAST(N'2024-03-29T00:00:00.000' AS DateTime), N'2023-24', 1, N'Susmita-DBA', CAST(N'2023-04-27T22:28:19.940' AS DateTime), NULL, NULL)
INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (2, 107, CAST(N'2023-04-01T00:00:00.000' AS DateTime), CAST(N'2024-03-29T00:00:00.000' AS DateTime), N'2023-24', 1, N'Susmita-DBA', CAST(N'2023-06-23T00:00:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (29, 108, CAST(N'2023-11-01T00:00:00.000' AS DateTime), CAST(N'2026-11-01T00:00:00.000' AS DateTime), N'2023-2026', 1, N'DBA', CAST(N'2023-11-28T12:35:27.810' AS DateTime), NULL, NULL)
INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (31, 116, CAST(N'2020-04-01T00:00:00.000' AS DateTime), CAST(N'2021-03-31T00:00:00.000' AS DateTime), N'2020-2021', 1, N'DBA', CAST(N'2024-02-07T00:00:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (32, 116, CAST(N'2023-04-01T00:00:00.000' AS DateTime), CAST(N'2024-03-31T00:00:00.000' AS DateTime), N'2023-2024', 1, N'DBA', CAST(N'2024-02-07T00:00:00.000' AS DateTime), NULL, NULL)
INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (33, 109, CAST(N'2025-01-01T00:00:00.000' AS DateTime), CAST(N'2025-12-29T00:00:00.000' AS DateTime), N'Adamas', 1, N'DBA', CAST(N'2024-03-14T15:17:28.307' AS DateTime), NULL, NULL)
INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (34, 112, CAST(N'2025-01-14T00:00:00.000' AS DateTime), CAST(N'2025-07-15T00:00:00.000' AS DateTime), N'Adamas', 1, N'DBA', CAST(N'2024-03-14T15:28:52.470' AS DateTime), NULL, NULL)
INSERT [dbo].[T_School_Academic_Session_Master] ([I_School_Session_ID], [I_Brand_ID], [Dt_Session_Start_Date], [Dt_Session_End_Date], [S_Label], [I_Status], [S_CreatedBy], [Dt_CreatedOn], [S_UpdatedBy], [Dt_UpdatedOn]) VALUES (35, 107, CAST(N'2024-04-01T00:00:00.000' AS DateTime), CAST(N'2025-03-31T00:00:00.000' AS DateTime), N'2024-25', 1, N'DBA', CAST(N'2024-03-15T12:17:33.570' AS DateTime), N'DBA', CAST(N'2024-04-01T18:25:11.430' AS DateTime))
SET IDENTITY_INSERT [dbo].[T_School_Academic_Session_Master] OFF
GO

