CREATE TABLE [dbo].[AdvSPTemp] (
    [I_Student_Detail_ID]  INT             NULL,
    [S_Mobile_No]          VARCHAR (500)   NULL,
    [S_Student_ID]         VARCHAR (500)   NULL,
    [I_Roll_No]            INT             NULL,
    [S_Student_Name]       VARCHAR (500)   NULL,
    [S_Invoice_No]         VARCHAR (100)   NULL,
    [S_Receipt_No]         VARCHAR (100)   NULL,
    [Dt_Invoice_Date]      DATETIME        NULL,
    [S_Component_Name]     VARCHAR (100)   NULL,
    [S_Batch_Name]         VARCHAR (100)   NULL,
    [S_Course_Name]        VARCHAR (100)   NULL,
    [I_Center_ID]          INT             NULL,
    [S_Center_Name]        VARCHAR (100)   NULL,
    [S_Brand_Name]         VARCHAR (100)   NULL,
    [S_Cost_Center]        VARCHAR (100)   NULL,
    [Due_Value]            REAL            NULL,
    [Dt_Installment_Date]  DATETIME        NULL,
    [I_Installment_No]     INT             NULL,
    [I_Parent_Invoice_ID]  INT             NULL,
    [I_Invoice_Detail_ID]  INT             NULL,
    [Revised_Invoice_Date] DATETIME        NULL,
    [Tax_Value]            DECIMAL (14, 2) NULL,
    [Total_Value]          DECIMAL (14, 2) NULL,
    [Amount_Paid]          DECIMAL (14, 2) NULL,
    [Tax_Paid]             DECIMAL (14, 2) NULL,
    [Total_Paid]           DECIMAL (14, 2) NULL,
    [MonthYear]            VARCHAR (20)    NULL,
    [instanceChain]        VARCHAR (200)   NULL
);

