CREATE TABLE [dbo].[T_Enquiry_External_Additional_Details] (
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [PreEnquiryID]          INT           NOT NULL,
    [ExtApplicationID]      VARCHAR (MAX) NULL,
    [FirstName]             VARCHAR (MAX) NOT NULL,
    [MiddleName]            VARCHAR (MAX) NULL,
    [LastName]              VARCHAR (MAX) NULL,
    [Centre]                VARCHAR (MAX) NULL,
    [MobileNo]              VARCHAR (MAX) NULL,
    [EmailID]               VARCHAR (MAX) NULL,
    [AlternateMobileNo]     VARCHAR (MAX) NULL,
    [DateofBirth]           DATETIME      NULL,
    [SalesDisposition]      VARCHAR (MAX) NULL,
    [DateofMaturityCC]      DATETIME      NULL,
    [DateofMaturitySales]   DATETIME      NULL,
    [Counsellor]            VARCHAR (MAX) NULL,
    [LeadCreatedBy]         VARCHAR (MAX) NULL,
    [Origin]                VARCHAR (MAX) NULL,
    [PrimaryTrafficChannel] VARCHAR (MAX) NULL,
    [InfoSource]            VARCHAR (MAX) NULL,
    [InfoMedium]            VARCHAR (MAX) NULL,
    [InfoCampaign]          VARCHAR (MAX) NULL,
    [HighestQualification]  VARCHAR (MAX) NULL,
    [Country]               VARCHAR (MAX) NULL,
    [State]                 VARCHAR (MAX) NULL,
    [District]              VARCHAR (MAX) NULL,
    [City]                  VARCHAR (MAX) NULL,
    [Pincode]               VARCHAR (MAX) NULL,
    [UserRegistrationDate]  DATETIME      NULL,
    [ExtSource]             VARCHAR (MAX) NULL,
    [CreatedBy]             VARCHAR (MAX) NULL,
    [CreatedOn]             DATETIME      NULL
);

