CREATE TABLE [dbo].[T_ERP_Student_Detail] (
    [I_Student_Detail_ID]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [R_I_Enquiry_Regn_ID]       BIGINT        NULL,
    [S_Student_ID]              VARCHAR (500) NULL,
    [S_Title]                   VARCHAR (10)  NULL,
    [S_First_Name]              VARCHAR (50)  NULL,
    [S_Middle_Name]             VARCHAR (50)  NULL,
    [S_Last_Name]               VARCHAR (50)  NULL,
    [Dt_Birth_Date]             DATETIME      NULL,
    [S_Age]                     VARCHAR (20)  NULL,
    [S_Email_ID]                VARCHAR (200) NULL,
    [S_Phone_No]                VARCHAR (20)  NULL,
    [S_Mobile_No]               VARCHAR (500) NULL,
    [I_Pref_Career_ID]          INT           NULL,
    [S_Curr_Address1]           VARCHAR (200) NULL,
    [S_Curr_Address2]           VARCHAR (200) NULL,
    [I_Curr_Country_ID]         INT           NULL,
    [I_Curr_State_ID]           INT           NULL,
    [I_Curr_City_ID]            INT           NULL,
    [S_Curr_Area]               VARCHAR (500) NULL,
    [S_Curr_Pincode]            VARCHAR (500) NULL,
    [S_Perm_Address1]           VARCHAR (200) NULL,
    [S_Perm_Address2]           VARCHAR (200) NULL,
    [I_Perm_Country_ID]         INT           NULL,
    [I_Perm_State_ID]           INT           NULL,
    [I_Perm_City_ID]            INT           NULL,
    [S_Perm_Area]               VARCHAR (500) NULL,
    [S_Perm_Pincode]            VARCHAR (500) NULL,
    [Is_Active]                 BIT           NOT NULL,
    [I_CreatedBy]               INT           NULL,
    [I_UpdatedBy]               INT           NULL,
    [Dtt_CreatedAt]             DATETIME      DEFAULT (getdate()) NULL,
    [Dtt_UpdatedAt]             DATETIME      NULL,
    [S_Conduct_Code]            VARCHAR (20)  NULL,
    [S_Is_Corporate]            BIT           NULL,
    [I_Corporate_ID]            INT           NULL,
    [I_RollNo]                  INT           NULL,
    [I_Marital_Status_ID]       INT           NULL,
    [I_Transport_ID]            INT           CONSTRAINT [DF_T_Student_Detail_I_Transport_ID_1] DEFAULT ((0)) NULL,
    [I_room_ID]                 INT           CONSTRAINT [DF_T_Student_Detail_I_room_ID_1] DEFAULT ((0)) NULL,
    [I_House_ID]                INT           NULL,
    [I_Route_ID]                INT           NULL,
    [B_Is_APAI_Acc_Settled]     BIT           NULL,
    [Dt_Transport_Deactivation] DATETIME      NULL,
    [B_IsBooking]               INT           CONSTRAINT [Df_Val_1] DEFAULT ((0)) NULL,
    [B_HasTakenLoan]            BIT           NULL,
    [I_DiscountType_ID]         INT           NULL,
    [S_Ext_Email_ID]            VARCHAR (MAX) NULL,
    [IsDropOut]                 BIT           NULL,
    [IsWaiting]                 BIT           NULL,
    [IsDefaulter]               BIT           NULL,
    [IsOnLeave]                 BIT           NULL,
    [IsCompleted]               BIT           NULL,
    [IsDiscontinued]            BIT           NULL,
    [DefaulterCourses]          VARCHAR (MAX) NULL,
    [PreDefaulterCourses]       VARCHAR (MAX) NULL,
    [I_buzzedDB_Slot_ID]        INT           NULL,
    [Student_Status]            INT           NULL,
    PRIMARY KEY CLUSTERED ([I_Student_Detail_ID] ASC)
);

