CREATE TABLE [dbo].[T_SMS_TYPE_MASTER] (
    [I_SMS_TYPE_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [S_SMS_TYPE_NAME]     VARCHAR (50)  NOT NULL,
    [S_SMS_BODY_TEMPLATE] VARCHAR (160) NOT NULL,
    [I_REFERENCE_TYPE_ID] INT           NOT NULL,
    [I_Status]            INT           NULL,
    [DLT_ID]              VARCHAR (MAX) NULL,
    [I_Brand_ID]          INT           NULL,
    CONSTRAINT [PK_T_SMS_TYPE_MASTER] PRIMARY KEY CLUSTERED ([I_SMS_TYPE_ID] ASC),
    CONSTRAINT [FK_T_SMS_TYPE_MASTER_T_SMS_REFERENCE_TYPE_MASTER] FOREIGN KEY ([I_REFERENCE_TYPE_ID]) REFERENCES [dbo].[T_SMS_REFERENCE_TYPE_MASTER] ([I_REFERENCE_TYPE_ID])
);

