CREATE TABLE [dbo].[T_SMS_PARAM_MASTER] (
    [I_PARAM_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [S_PARAM_NAME]  VARCHAR (50)  NOT NULL,
    [S_PARAM_VALUE] VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_T_SMS_PARAM_MASTER] PRIMARY KEY CLUSTERED ([I_PARAM_ID] ASC)
);

