CREATE TABLE [ACADEMICS].[T_Training_Feedback_Details] (
    [I_Training_Feedback_Detail_ID] INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [I_Training_Feedback_ID]        INT          NULL,
    [I_Feedback_Option_Master_ID]   INT          NULL,
    [S_Crtd_By]                     VARCHAR (20) NULL,
    [S_Upd_By]                      VARCHAR (20) NULL,
    [Dt_Crtd_On]                    DATETIME     NULL,
    [Dt_Upd_On]                     DATETIME     NULL,
    CONSTRAINT [PK__T_Training_Feedb__6502C82F] PRIMARY KEY CLUSTERED ([I_Training_Feedback_Detail_ID] ASC),
    CONSTRAINT [FK__T_Trainin__I_Fee__70C98096] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__71BDA4CF] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__72B1C908] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__73A5ED41] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__749A117A] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__758E35B3] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__768259EC] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__77767E25] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__786AA25E] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__795EC697] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Fee__7A52EAD0] FOREIGN KEY ([I_Feedback_Option_Master_ID]) REFERENCES [ACADEMICS].[T_Feedback_Option_Master] ([I_Feedback_Option_Master_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__000BC426] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__00FFE85F] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__01F40C98] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__02E830D1] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__03DC550A] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__04D07943] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__1A87B4A6] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__1B7BD8DF] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__1C6FFD18] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__1D642151] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__1E58458A] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__1F4C69C3] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__20408DFC] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__2134B235] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__2228D66E] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__231CFAA7] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__24111EE0] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__7B470F09] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__7C3B3342] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__7D2F577B] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__7E237BB4] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID]),
    CONSTRAINT [FK__T_Trainin__I_Tra__7F179FED] FOREIGN KEY ([I_Training_Feedback_ID]) REFERENCES [ACADEMICS].[T_Training_Feedback] ([I_Training_Feedback_ID])
);

